# -*- coding: utf-8 -*-
"""Essay_Points.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b92ETnrmdxZNvnJ4ld-8LZV-BElfyI0D
"""

import numpy as np
import pandas as pd
from textblob import TextBlob

from google.colab import drive
drive.mount('/content/drive')

Data = pd.read_csv('/content/drive/My Drive/donorschoose/Projects.csv')

df = pd.DataFrame(Data)
column = df['Project Essay']
count_row = df['Project Essay'].shape[0]
df["Essay Points"] = ""
Essay_points = df["Essay Points"]

for i in range(count_row):
      if(pd.isnull(column[i])):
         Essay_points[i]=0
      else:
        analysis = TextBlob(column[i])
        pol = analysis.sentiment.polarity
        sub = analysis.sentiment.subjectivity
        Essay_points[i]= (pol*0.6 + sub*0.4)*100
    
      
df

